const storybookData = {
  items: [
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2528975,
      name: "javascript",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2192494,
      name: "python",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1917357,
      name: "java",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1615138,
      name: "c#",
    },
    {
      collectives: [
        {
          tags: ["php"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective where developers working with PHP can learn and connect about the open source scripting language.",
          link: "/collectives/php",
          name: "PHP",
          slug: "php",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1464488,
      name: "php",
    },
    {
      collectives: [
        {
          tags: ["android", "ios"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
          link: "/collectives/mobile-dev",
          name: "Mobile Development",
          slug: "mobile-dev",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1417264,
      name: "android",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1187364,
      name: "html",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1034798,
      name: "jquery",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 806774,
      name: "c++",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 804250,
      name: "css",
    },
    {
      collectives: [
        {
          tags: ["android", "ios"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
          link: "/collectives/mobile-dev",
          name: "Mobile Development",
          slug: "mobile-dev",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 687272,
      name: "ios",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 670795,
      name: "sql",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 662019,
      name: "mysql",
    },
    {
      collectives: [
        {
          tags: [
            "stringr",
            "r-raster",
            "r",
            "shinyapps",
            "readr",
            "ggplot2",
            "knitr",
            "r-caret",
            "shinydashboard",
            "quantmod",
            "zoo",
            "tibble",
            "rlang",
            "data.table",
            "dtplyr",
            "forcats",
            "tidyr",
            "plyr",
            "shiny-server",
            "lubridate",
            "shiny",
            "dplyr",
            "purrr",
            "tidyverse",
            "rstudio",
            "rvest",
            "r-package",
          ],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective where data scientists and AI researchers gather to find, share, and learn about R and other subtags like knitr and dplyr.",
          link: "/collectives/r-language",
          name: "R Language",
          slug: "r-language",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 505666,
      name: "r",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 476753,
      name: "reactjs",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 472032,
      name: "node.js",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 416719,
      name: "arrays",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 403988,
      name: "c",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 374622,
      name: "asp.net",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 360345,
      name: "json",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 343661,
      name: "python-3.x",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 338056,
      name: "ruby-on-rails",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 337910,
      name: ".net",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 334559,
      name: "sql-server",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 333424,
      name: "swift",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 311844,
      name: "django",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 304148,
      name: "angular",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 292327,
      name: "objective-c",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 286663,
      name: "pandas",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 286509,
      name: "excel",
    },
  ],
  has_more: true,
  quota_max: 300,
  quota_remaining: 42,
};

export default storybookData;
